export const formFields = [
    {
        label: 'First name',
        required: true,
        type: 'text',
        placeholder: 'First name',
        // value: formState.firstName,
        name: 'firstName',
    },
    {
        label: 'Last name',
        required: false,
        type: 'text',
        placeholder: 'Last name',
        // value: formState.lastName,
        name: 'lastName',
    },
    // {
    //     label: 'E-mail',
    //     required: true,
    //     type: 'email',
    //     placeholder: 'E-mail Id',
    //     // value: formState.email,
    //     name: 'email',
    // },
    {
        label: 'Contact No.',
        required: true,
        type: 'text',
        placeholder: 'Phone Number / Email',
        // value: formState.contactNo,
        name: 'contactNo',
    },
    {
        label: 'Password',
        required: true,
        type: 'password',
        placeholder: 'Password',
        // value: formState.password,
        name: 'password',
    },
    {
        label: 'Confirm Password',
        required: true,
        type: 'password',
        placeholder: 'Re-Enter password',
        // value: formState.confirmPassword,
        name: 'confirmPassword',
    },
]
