export const formFields = [
    {
        label: 'First name',
        required: true,
        type: 'text',
        placeholder: 'First name',
        // value: formState.firstName,
        name: 'firstName',
    },
    {
        label: 'Last name',
        required: false,
        type: 'text',
        placeholder: 'Last name',
        // value: formState.lastName,
        name: 'lastName',
    },
    {
        label: 'E-mail',
        required: true,
        type: 'email',
        placeholder: 'Enter your E-mail address',
        // value: formState.email,
        name: 'email',
    },
    {
        label: 'Contact No.',
        required: true,
        type: 'text',
        placeholder: 'Enter your phone number',
        // value: formState.contactNo,
        name: 'contactNo',
    },
    {
        label: 'Password',
        required: true,
        type: 'text',
        placeholder: 'Enter your password',
        // value: formState.password,
        name: 'password',
    },
    {
        label: 'Confirm Password',
        required: true,
        type: 'text',
        placeholder: 'Re-Enter your password',
        // value: formState.confirmPassword,
        name: 'confirmPassword',
    },
]
